Wed Aug 30 16:00:50 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0388F8B0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:01:55 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x038A21B0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:03:43 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0300F8B0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:05:04 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x030ECB10>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:06:09 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0310FEB0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:07:07 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0326C7B0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:07:34 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03281350>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Wed Aug 30 16:08:11 2017 | 	unknow error:Can't convert 'dict' object to str implicitly
Wed Aug 30 16:09:01 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0364DAB0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'comcode': None, 'if_interval': None, 'genius_uid': None, 'startdate': '2017-02-27T00:00:00', 'isvalid': None, 'mtime': '2017-02-22T17:21:47', 'seq': None, 'date_type_code': None, 'enddate': None, 'iss_id': None, 'ctime': '2017-02-22T17:40:49'}
Wed Aug 30 16:11:41 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0311EA90>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'genius_uid': None, 'mtime': '2017-02-22T17:21:47', 'iss_id': None, 'seq': None, 'enddate': None, 'startdate': '2017-02-27T00:00:00', 'date_type_code': None, 'comcode': None, 'ctime': '2017-02-22T17:40:49', 'isvalid': None, 'if_interval': None}
Wed Aug 30 16:12:21 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0367EAB0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'date_type_code': None, 'seq': None, 'startdate': '2017-02-27T00:00:00', 'mtime': '2017-02-22T17:21:47', 'isvalid': None, 'enddate': None, 'ctime': '2017-02-22T17:40:49', 'genius_uid': None, 'if_interval': None, 'comcode': None, 'iss_id': None}
Wed Aug 30 16:12:55 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03D0EA50>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'isvalid': None, 'mtime': '2017-02-22T17:21:47', 'startdate': '2017-02-27T00:00:00', 'genius_uid': None, 'comcode': None, 'date_type_code': None, 'if_interval': None, 'iss_id': None, 'seq': None, 'ctime': '2017-02-22T17:40:49', 'enddate': None}
Wed Aug 30 16:19:36 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03BCC7B0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'startdate': '2017-02-27T00:00:00', 'isvalid': None, 'if_interval': None, 'date_type_code': None, 'ctime': '2017-02-22T17:40:49', 'genius_uid': None, 'seq': None, 'enddate': None, 'mtime': '2017-02-22T17:21:47', 'iss_id': None, 'comcode': None}
Wed Aug 30 16:20:03 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03BE10F0>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'startdate': '2016-12-02T00:00:00', 'isvalid': None, 'if_interval': None, 'date_type_code': None, 'ctime': '2017-02-22T17:40:49', 'genius_uid': None, 'seq': None, 'enddate': None, 'mtime': '2017-02-22T17:21:48', 'iss_id': None, 'comcode': None}
Wed Aug 30 16:20:30 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03BED810>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
data:{'startdate': '2016-12-09T00:00:00', 'isvalid': None, 'if_interval': None, 'date_type_code': None, 'ctime': '2017-02-22T17:40:49', 'genius_uid': None, 'seq': None, 'enddate': '2016-12-11T00:00:00', 'mtime': '2017-02-22T17:21:48', 'iss_id': None, 'comcode': None}
